services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend/src:/app/src
    environment:
      ACCESS_TOKEN_SECRET: uenimrgkjhrfugbzsyebyugr

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  piston:
    image: ghcr.io/engineer-man/piston
    container_name: piston_api
    restart: always
    ports:
      - 2000:2000
    volumes:
      - ./data/piston/packages:/piston/packages
    tmpfs:
      - /piston/jobs:exec,uid=1000,gid=1000,mode=711
      - /tmp:exec