services:
  backend:
    image: alphapwnd/wild-code-online-backend
    ports:
      - 5000:5000
    volumes:
      - ./backend/src:/app/src
    env_file: ./backend/.env

  frontend:
    image: alphapwnd/wild-code-online-frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
    env_file: ./frontend/.env

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file: ./backend/.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  piston:
    image: ghcr.io/engineer-man/piston
    container_name: piston_api
    restart: always
    ports:
      - 2000:2000
    volumes:
      - ./data/piston/packages:/piston/packages
    tmpfs:
      - /piston/jobs:exec,uid=1000,gid=1000,mode=711
      - /tmp:exec

  nginx:
    image: nginx:1.21.3
    depends_on: 
      - backend
      - frontend
    restart: always
    ports: 
      - ${GATEWAY_PORT:-8000}:80
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
